Switch to more modern password storage
rc4 and md5 have been considered obsolete for years, so let's switch to
something more modern: scrypt and aes.

By keeping the old md5/arc password checkers/decoders, we remain
backwards compatible with old configfiles and xml files, but we will
only write new data using the more secure hashing and encryption.

First hashing: scrypt. Consensus in the crypto community is that scrypt
is the best key distribution function today, and the recommended way to
hash passwords. Using libscrypt, we get sensible defaults, sensible IV's
and automatic encoding. Let's use that for user, oper and auth
passwords. We can recognize scrypt hashes by their prefix ($) and length
(120+), so we automatically detect whether we need to check against an
scrypt hash instead of plain text passwords or old-style md5 hashes.

Then encryption: AES-GCM. AES is modern, supported by all the SSL
libraries we support and using it in counter mode we can even check
whether password decryption failed and fall back to our old arc scheme
for backwards compatibility. Instead of rolling our own AEC-GCM
implementation, we use what gnutls/nss/openssl have to offer, which does
unfortunately mean it had to be implemtented thrice. The implementations
are completely compatible and files written by bitlbee compiled with
gnutls can be read by bitlbee compiled with nss or openssl and vice
versa.

And finally, update the example configfile to not have old-style hashes
in it and rip out arc_encode and its tests.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -626,6 +626,14 @@ else
 	echo 'Insufficient resolv routines. Jabber server must be set explicitly'
 fi
 
+if echo '#include <libscrypt.h>' | $CC -E - >/dev/null 2>/dev/null; then
+	echo EFLAGS+=-lscrypt >> Makefile.settings
+else
+	echo
+	echo 'Cannot find libscrypt development libraries, aborting. (Install libscrypt-dev?)'
+	exit 1
+fi
+
 
 STORAGES="xml"
 
