Import BitlBee 0.90 from tarball

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22,8 +22,8 @@ yahoo=1
 debug=0
 strip=1
 tcpd=0
-iconv=1
 flood=0
+ssl=auto
 
 arch=`uname -s`
 cpu=`uname -m`
@@ -54,8 +54,9 @@ Option		Description				Default
 --debug=0/1	Disable/enable debugging		$debug
 --strip=0/1	Disable/enable binary stripping		$strip
 
---iconv=0/1	Character set conversion		$iconv
 --flood=0/1	Flood protection			$flood
+
+--ssl=...	SSL library to use (gnutls, nss, auto)	$ssl
 EOF
 		exit;
 	fi
@@ -63,12 +64,12 @@ EOF
 	shift;
 done
 
-# Expand $prefix
-bindir=`eval echo $bindir/ | sed 's/\/\+/\//g'`
-etcdir=`eval echo $etcdir/ | sed 's/\/\+/\//g'`
-mandir=`eval echo $mandir/ | sed 's/\/\+/\//g'`
-datadir=`eval echo $datadir/ | sed 's/\/\+/\//g'`
-config=`eval echo $config/ | sed 's/\/\+/\//g'`
+# Expand $prefix and get rid of double slashes
+bindir=`eval echo "$bindir/" | sed 's/\/\{1,\}/\//g'`
+etcdir=`eval echo "$etcdir/" | sed 's/\/\{1,\}/\//g'`
+mandir=`eval echo "$mandir/" | sed 's/\/\{1,\}/\//g'`
+datadir=`eval echo "$datadir/" | sed 's/\/\{1,\}/\//g'`
+config=`eval echo "$config/" | sed 's/\/\{1,\}/\//g'`
 
 cat<<EOF>Makefile.settings
 ## BitlBee settings, generated by configure
@@ -99,6 +100,7 @@ cat<<EOF>config.h
 #define DATADIR "$datadir"
 #define ARCH "$arch"
 #define CPU "$cpu"
+#define IPV6
 EOF
 
 if [ "$debug" = "1" ]; then
@@ -162,35 +164,62 @@ else
 	echo '#define NO_TCPD' >> config.h
 fi
 
-echo '#define ICONV' >> config.h
-if [ -e /usr/include/iconv.h -a "$iconv" = "1" ]; then
-	:;
-	## no-op
-elif [ -e /usr/local/include/iconv.h -a "$iconv" = "1" ]; then
-	cat<<EOF>>Makefile.settings
-EFLAGS+=-L/usr/local/lib
-CFLAGS+=-I/usr/local/include
-EOF
-else
-	if ! [ "$iconv" = 0 ]; then
-		iconv=0
-		echo
-		echo 'Compiling without iconv support, could not find include file.';
-	fi
-	echo '#undef ICONV' >> config.h
-fi
-
-if [ "$msn" = 1 ]; then
+detect_gnutls()
+{
 	if libgnutls-config --version > /dev/null 2> /dev/null; then
 		cat <<EOF>>Makefile.settings
+SSL_CLIENT=ssl_client.o
 EFLAGS+=`libgnutls-config --libs`
 CFLAGS+=`libgnutls-config --cflags`
 EOF
-		echo '#define USE_GNUTLS' >> config.h
+		echo '#define USE_GNUTLS' >> config.h;
+		
+		ssl=gnutls
+		ret=1;
+	else
+		ret=0;
+	fi;
+}
+
+detect_nss()
+{
+	if type pkg-config > /dev/null 2>/dev/null && pkg-config mozilla-nss; then
+		cat<<EOF>>Makefile.settings
+SSL_CLIENT=nss_client.o
+EFLAGS+=`pkg-config --libs mozilla-nss`
+CFLAGS+=`pkg-config --cflags mozilla-nss`
+EOF
+		
+		ssl=nss
+		ret=1;
+	else
+		ret=0;
+	fi;
+}
+
+if [ "$msn" = 1 ]; then
+	if [ "$ssl" = "auto" ]; then
+		detect_gnutls
+		if [ "$ret" = "0" ]; then
+			detect_nss
+		fi;
+	elif [ "$ssl" = "gnutls" ]; then
+		detect_gnutls;
+	elif [ "$ssl" = "nss" ]; then
+		detect_nss;
 	else
 		echo
-		echo 'WARNING: Could not find libgnutls, we need that for MSN. MSN disabled.'
-		msn=0;
+		echo 'ERROR: Unknown SSL library specified.'
+		exit 1;
+	fi
+	
+	if [ "$ret" = "0" ]; then
+		echo
+		echo 'WARNING: Could not find a suitable SSL library (GnuTLS or libnss). This is'
+		echo '         necessary for MSN support. To continue, install a suitable SSL library'
+		echo '         or disable MSN support (--msn=0).'
+		
+		exit 1;
 	fi;
 fi
 
@@ -277,22 +306,13 @@ Linux )
 ;;
 *BSD )
 	echo 'Although our primary development system is Linux, BitlBee should run quite well on most BSD systems.'
-	if [ "$iconv" = 1 ]; then
-		echo 'EFLAGS+=-liconv' >> Makefile.settings;
-	fi
 ;;
 SunOS )
 	echo 'Solaris does not work with stripping enabled, so we will disable that.'
 	echo 'EFLAGS+=-lresolv -lnsl -lsocket' >> Makefile.settings
 	echo 'STRIP=\# skip strip' >> Makefile.settings
-	if [ "$iconv" = "1" ]; then
-		echo 'EFLAGS+=-liconv' >> Makefile.settings;
-	fi
 ;;
 Darwin )
-	if [ "$iconv" = "1" ]; then
-		echo 'EFLAGS+=-liconv' >> Makefile.settings;
-	fi
 	echo 'Darwin/Mac OS X. This should work well, please read the docs for more information.'
 ;;
 IRIX )
@@ -330,10 +350,8 @@ else
 	echo '       really make sense in inetd services anyway.';
 fi
 
-if [ "$iconv" = "0" ]; then
-	echo '  Iconv support disabled.';
-else
-	echo '  Iconv support enabled.';
+if [ "$msn" = "1" ]; then
+	echo '  Using SSL library: '$ssl;
 fi
 
 if [ "$flood" = "0" ]; then
